#!/usr/bin/env php
<?php
if (!isset($argv[1])) {
    echo "Specify the repository to check the documentation.\n";
    echo "Usage: php check-docs <repo_name>\n";
    exit;
}
$repo = $argv[1];
$repoDir = "../$repo";

if (!file_exists($repoDir)) {
    echo "Repository $repo doesn't exist.\n";
    exit;
}

$curDir = getcwd();
chdir($repoDir);

echo "Checking the guide of $repo ...\n";

$outFile = "../yii2-ja/translation-check/$repo.html";
$tempFile = "../yii2-ja/translation-check/temp.html";

exec("php ../yii2/build/build translation docs/guide docs/guide-ja $repo > $tempFile");

$outContent = @file_get_contents($outFile);
if ($outContent === false) {
    copy($tempFile, $outFile);
} else {
    $tempContent = file_get_contents($tempFile);
    if (strcmp($outContent, $tempContent) !== 0) {
        copy($tempFile, $outFile);
    }
}

if ($repo === 'yii2') {
    echo "Checking the internal documentss of $repo ...\n";

    $outFile = "../yii2-ja/translation-check/internals.html";

    exec("php ../yii2/build/build translation docs/internals docs/internals-ja internals > $tempFile");

    $outContent = @file_get_contents($outFile);
    if ($outContent === false) {
        copy($tempFile, $outFile);
    } else {
        $tempContent = file_get_contents($tempFile);
        if (strcmp($outContent, $tempContent) !== 0) {
            copy($tempFile, $outFile);
        }
    }
}

echo "Check done successfully.\n";

chdir($curDir);
